In [7]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int64')

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.shape)

(3,)


In [12]:
print(a.shape)

(3,)


In [13]:
print(a[1])

2


In [14]:
a[0] = 3

In [15]:
print (a)

[3 2 3]


In [19]:
a2d = np.array([[1,2,3],[4,5,6]])

In [17]:
print(a2d)
print(a2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
a2d[1:,:2]

array([[4, 5]])

In [9]:
print(type(a2d))

<class 'numpy.ndarray'>


In [12]:
a2d.dtype

dtype('int64')

In [13]:
a2d[0,2]

3

In [28]:
a = np.array([1.0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

b = a.reshape(4,4)

In [32]:
np.linspace(0,1,10)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [30]:
b.dtype

dtype('float64')

In [17]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [36]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
ide = np.diag([1,2,3,4,5])

In [34]:
ide

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [37]:
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [24]:
b[1:,1:]

array([[ 6.,  7.,  8.],
       [10., 11., 12.],
       [14., 15., 16.]], dtype=float32)

In [25]:
b[:1,:]

array([[1., 2., 3., 4.]], dtype=float32)

In [26]:
print(list(range(1,10,2)))

[1, 3, 5, 7, 9]


In [27]:
b[::2,::3]

array([[ 1.,  4.],
       [ 9., 12.]], dtype=float32)

In [43]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

arr1 = arr1.reshape(4,4)

print(arr1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [44]:
arr2 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160],np.float32)

arr2 = arr2.reshape(4,4)

print(arr2)

[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]]


In [45]:
print(arr1-arr2)

[[  -9.  -18.  -27.  -36.]
 [ -45.  -54.  -63.  -72.]
 [ -81.  -90.  -99. -108.]
 [-117. -126. -135. -144.]]


In [31]:
print(np.add(arr1,arr2))

[[ 11.  22.  33.  44.]
 [ 55.  66.  77.  88.]
 [ 99. 110. 121. 132.]
 [143. 154. 165. 176.]]


In [32]:
print(np.subtract(arr1,arr2))

[[  -9.  -18.  -27.  -36.]
 [ -45.  -54.  -63.  -72.]
 [ -81.  -90.  -99. -108.]
 [-117. -126. -135. -144.]]


In [33]:
print(np.multiply(arr1,arr2))

[[  10.   40.   90.  160.]
 [ 250.  360.  490.  640.]
 [ 810. 1000. 1210. 1440.]
 [1690. 1960. 2250. 2560.]]


In [34]:
print(np.divide(arr1,arr2))

[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]


In [35]:
arr1.dot(arr2)

array([[ 900., 1000., 1100., 1200.],
       [2020., 2280., 2540., 2800.],
       [3140., 3560., 3980., 4400.],
       [4260., 4840., 5420., 6000.]], dtype=float32)

In [38]:
#Broadcasting in numpy


a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10],[40]])
print(a)
print(b)


[[1 2 3]
 [4 5 6]]
[[10]
 [40]]


In [40]:
a = np.array([1,2,3])
b = np.array([2])
c = a+b


In [41]:
c

array([3, 4, 5])

In [46]:
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [47]:
arr1.sum()

136.0

In [49]:
arr1.sum(axis=0)

array([28., 32., 36., 40.], dtype=float32)

In [50]:
arr1.sum(axis=1)

array([10., 26., 42., 58.], dtype=float32)

In [52]:
arr1.max(axis=0)

array([13., 14., 15., 16.], dtype=float32)

In [53]:
arr1.mean()

8.5

In [54]:
arr1.mean(axis=0)

array([ 7.,  8.,  9., 10.], dtype=float32)

In [37]:
np.add(a,b)

[[10,10,10],[40,40,40]]

[[10, 10, 10], [40, 40, 40]]

In [38]:
np.sum(a)

21

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.mean(a,axis=1)

array([2., 5.])

In [41]:
np.std(a,axis = 0)

array([1.5, 1.5, 1.5])

In [56]:
arr1.T

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]], dtype=float32)

In [85]:
np.random.rand(2,2)

#print(np.random.rand.__doc__)

array([[0.88972032, 0.89454065],
       [0.94103989, 0.9950041 ]])

In [95]:
np.empty([2,2])

array([[0.88972032, 0.89454065],
       [0.94103989, 0.9950041 ]])